#!/bin/bash
#
# NAS FOLDERS / PERMISSIONS / EXPORT - clnvrr050
#
# Generated by generate_nas_scripts.py
#
set -e


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic051rp
# RESOURCE GROUP: clnvrm051
# SERVICE: clnvrm051_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02/etc/picata


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic052rp
# RESOURCE GROUP: clnvrm052
# SERVICE: clnvrm052_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02/etc/picata


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic053rp
# RESOURCE GROUP: clnvrm053
# SERVICE: clnvrm053_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02/etc/picata


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic054rp
# RESOURCE GROUP: clnvrm054
# SERVICE: clnvrm054_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02/etc/picata


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic055rp
# RESOURCE GROUP: clnvrm055
# SERVICE: clnvrm055_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02/etc/picata


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic056rp
# RESOURCE GROUP: clnvrm056
# SERVICE: clnvrm056_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02/etc/picata


################################################
# CLUSTER: clnvrr050
# CLUSTER NAME: TVSNVRCLU050RP
# PICATA RG: tvsnvrpic057rp
# RESOURCE GROUP: clnvrm057
# SERVICE: clnvrm057_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02/etc/picata


################################################
# CLUSTER ROOT NFS EXPORT
################################################

# --------------------------------------------------------
# NFS EXPORT - CLUSTER ROOT ONLY
# --------------------------------------------------------

EXPORT_PATH=/ifs/infstonas001rp/mtr-rec/clnvrr050

# Check whether the cluster-root export already exists.
EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

if [[ -z "$EXPORT_ID" ]]; then
    echo "NFS export does not exist. Creating: $EXPORT_PATH"
    isi nfs exports create "$EXPORT_PATH" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    # Get the newly created export ID.
    EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

    if [[ -z "$EXPORT_ID" ]]; then
        echo "ERROR: NFS export was created but its ID could not be found."
        exit 1
    fi

    echo "NFS export created: $EXPORT_PATH (ID $EXPORT_ID)"
else
    echo "NFS export already exists: $EXPORT_PATH (ID $EXPORT_ID)"
    echo "Updating NFS export parameters..."

    isi nfs exports modify "$EXPORT_ID" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export updated: $EXPORT_PATH (ID $EXPORT_ID)"
fi


echo ""
echo "Completed NAS folders, permissions and NFS export for clnvrr050"
