#!/bin/bash
#
# NAS FOLDERS / PERMISSIONS / EXPORT - clnvrr090
#
# Generated by generate_nas_scripts.py
#
set -e


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic091rp
# RESOURCE GROUP: clnvrm091
# SERVICE: clnvrm091_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02/etc/picata


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic092rp
# RESOURCE GROUP: clnvrm092
# SERVICE: clnvrm092_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02/etc/picata


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic093rp
# RESOURCE GROUP: clnvrm093
# SERVICE: clnvrm093_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02/etc/picata


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic094rp
# RESOURCE GROUP: clnvrm094
# SERVICE: clnvrm094_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02/etc/picata


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic095rp
# RESOURCE GROUP: clnvrm095
# SERVICE: clnvrm095_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02/etc/picata


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic096rp
# RESOURCE GROUP: clnvrm096
# SERVICE: clnvrm096_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02/etc/picata


################################################
# CLUSTER: clnvrr090
# CLUSTER NAME: TVSNVRCLU090RP
# PICATA RG: tvsnvrpic097rp
# RESOURCE GROUP: clnvrm097
# SERVICE: clnvrm097_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02/etc/picata


################################################
# CLUSTER ROOT NFS EXPORT
################################################

# --------------------------------------------------------
# NFS EXPORT - CLUSTER ROOT ONLY
# --------------------------------------------------------

EXPORT_PATH=/ifs/infstonas001rp/mtr-rec/clnvrr090

# Check whether the cluster-root export already exists.
EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

if [[ -z "$EXPORT_ID" ]]; then
    echo "NFS export does not exist. Creating: $EXPORT_PATH"
    isi nfs exports create "$EXPORT_PATH" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    # Get the newly created export ID.
    EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

    if [[ -z "$EXPORT_ID" ]]; then
        echo "ERROR: NFS export was created but its ID could not be found."
        exit 1
    fi

    echo "NFS export created: $EXPORT_PATH (ID $EXPORT_ID)"
else
    echo "NFS export already exists: $EXPORT_PATH (ID $EXPORT_ID)"
    echo "Updating NFS export parameters..."

    isi nfs exports modify "$EXPORT_ID" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export updated: $EXPORT_PATH (ID $EXPORT_ID)"
fi


echo ""
echo "Completed NAS folders, permissions and NFS export for clnvrr090"
