#!/bin/bash
#
# NAS QUOTAS - clnvrr050
#
# Generated by generate_nas_scripts.py
#
set -e

# --------------------------------------------------------
# QUOTA: clnvrm051_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm051/clnvrm051_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm052_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm052/clnvrm052_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm053_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm053/clnvrm053_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm054_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm054/clnvrm054_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm055_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm055/clnvrm055_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm056_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm056/clnvrm056_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm057_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr050/clnvrm057/clnvrm057_p02 directory --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrr050"
