#!/bin/bash
#
# NAS QUOTAS - clnvrm090
#
# Generated by generate_nas_scripts.py
#
set -e

# This script is idempotent.
# Existing directories are preserved.
# Ownership/mode are corrected only when required.

# --------------------------------------------------------
# QUOTA: clnvrm091
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm091

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm092
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm092

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm093
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm093

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm094
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm094

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm095
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm095

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm096
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm096

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm097
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm090/clnvrm097

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrm090"
