#!/bin/bash
#
# NAS QUOTAS - clnvrr060
#
# Generated by generate_nas_scripts.py
#
set -e

# --------------------------------------------------------
# QUOTA: clnvrm061_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm062_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm063_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm064_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm065_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm066_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm067_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02 directory --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrr060"
