#!/bin/bash
#
# NAS QUOTAS - clnvrm100
#
# Generated by generate_nas_scripts.py
#
set -e

# This script is idempotent.
# Existing directories are preserved.
# Ownership/mode are corrected only when required.

# --------------------------------------------------------
# QUOTA: clnvrm101
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrm100"
