#!/bin/bash
#
# NAS FOLDERS / PERMISSIONS / NFS - clnvrm100
#
# Generated by generate_nas_scripts.py
#
set -e

# This script is idempotent.
# Existing directories are preserved.
# Ownership/mode are corrected only when required.


################################################
# CLUSTER ROOT
################################################

# CLUSTER ROOT
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100
fi


################################################
# CLUSTER: clnvrm100
# CLUSTER NAME: TVSNVRCLU100MP
# TYPE: 1+1
# PICATA RG: tvsnvrpic101mp
# RESOURCE GROUP: clnvrm101
################################################

# RESOURCE GROUP ROOT
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101
fi

# --------------------------------------------------------
# RESOURCE GROUP BASE DIRECTORIES
# --------------------------------------------------------

# APP directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/app
fi

# ETC directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc
fi

# DATA directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/data
fi

# LOG directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "root:wheel" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> root:wheel"
        chown root:wheel /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log
    chown root:wheel /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/log
fi

# --------------------------------------------------------
# PICATA ETC STRUCTURE
# --------------------------------------------------------

# PICATA configuration root
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata
fi

# PICATA area-LQ directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ
fi

# PICATA alarms directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/alarms
fi

# PICATA records directory
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "755" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 755"
        chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records
    chmod 755 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/etc/picata/area-LQ/records
fi

# --------------------------------------------------------
# PICATA SERVICE DIRECTORIES
# --------------------------------------------------------

# PICATA service directory clnvrm101_p01
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p01
fi

# PICATA service directory clnvrm101_p02
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p02
fi

# PICATA service directory clnvrm101_p03
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p03
fi

# PICATA service directory clnvrm101_p04
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p04
fi

# PICATA service directory clnvrm101_p05
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p05
fi

# PICATA service directory clnvrm101_p06
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p06
fi

# PICATA service directory clnvrm101_p07
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p07
fi

# PICATA service directory clnvrm101_p08
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p08
fi

# PICATA service directory clnvrm101_p09
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p09
fi

# PICATA service directory clnvrm101_p10
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p10
fi

# PICATA service directory clnvrm101_p11
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p11
fi

# PICATA service directory clnvrm101_p12
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p12
fi

# PICATA service directory clnvrm101_p13
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p13
fi

# PICATA service directory clnvrm101_p14
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p14
fi

# PICATA service directory clnvrm101_p15
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p15
fi

# PICATA service directory clnvrm101_p16
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p16
fi

# PICATA service directory clnvrm101_p17
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p17
fi

# PICATA service directory clnvrm101_p18
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p18
fi

# PICATA service directory clnvrm101_p19
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p19
fi

# PICATA service directory clnvrm101_p20
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p20
fi

# PICATA service directory clnvrm101_p21
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p21
fi

# PICATA service directory clnvrm101_p22
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p22
fi

# PICATA service directory clnvrm101_p23
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p23
fi

# PICATA service directory clnvrm101_p24
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p24
fi

# PICATA service directory clnvrm101_p25
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p25
fi

# PICATA service directory clnvrm101_p26
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p26
fi

# PICATA service directory clnvrm101_p27
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p27
fi

# PICATA service directory clnvrm101_p28
if [[ -d /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28 ]]; then
    echo "Directory exists: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28"

    CURRENT_OWNER=$(stat -c '%U' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28 2>/dev/null || true)
    CURRENT_GROUP=$(stat -c '%G' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28 2>/dev/null || true)
    CURRENT_MODE=$(stat -c '%a' /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28 2>/dev/null || true)

    if [[ "$CURRENT_OWNER:$CURRENT_GROUP" != "recorder:recorder" ]]; then
        echo "  Fixing owner/group: $CURRENT_OWNER:$CURRENT_GROUP -> recorder:recorder"
        chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28
    else
        echo "  Owner/group OK: $CURRENT_OWNER:$CURRENT_GROUP"
    fi

    if [[ "$CURRENT_MODE" != "700" ]]; then
        echo "  Fixing mode: $CURRENT_MODE -> 700"
        chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28
    else
        echo "  Mode OK: $CURRENT_MODE"
    fi
else
    echo "Directory does not exist. Creating: /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28"
    mkdir -p /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28
    chown recorder:recorder /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28
    chmod 700 /ifs/infstonas001mp/mtr-rec/clnvrm100/clnvrm101/clnvrm101_p28
fi


################################################
# CLUSTER ROOT NFS EXPORT
################################################

# --------------------------------------------------------
# NFS EXPORT - CLUSTER ROOT ONLY
# --------------------------------------------------------

EXPORT_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm100

echo "Checking NFS export: $EXPORT_PATH"

# Find an existing export for this exact path.
EXPORT_ID=$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')

if [[ -z "$EXPORT_ID" ]]; then
    echo "NFS export does not exist. Creating: $EXPORT_PATH"

    isi nfs exports create "$EXPORT_PATH" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export created: $EXPORT_PATH"
else
    echo "NFS export already exists: $EXPORT_PATH (ID $EXPORT_ID)"
    echo "Checking/updating required NFS parameters..."

    isi nfs exports modify "$EXPORT_ID" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export updated: $EXPORT_PATH (ID $EXPORT_ID)"
fi


echo ""
echo "Completed NAS folders, permissions and NFS export for clnvrm100"
