#!/bin/bash
#
# NAS QUOTAS - clnvrr090
#
# Generated by generate_nas_scripts.py
#
set -e

# --------------------------------------------------------
# QUOTA: clnvrm091_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm091/clnvrm091_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm092_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm092/clnvrm092_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm093_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm093/clnvrm093_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm094_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm094/clnvrm094_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm095_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm095/clnvrm095_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm096_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm096/clnvrm096_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm097_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr090/clnvrm097/clnvrm097_p02 directory --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrr090"
