#!/bin/bash
#
# NAS QUOTAS - clnvrr070
#
# Generated by generate_nas_scripts.py
#
set -e

# --------------------------------------------------------
# QUOTA: clnvrm071_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm072_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm073_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm074_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm075_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm076_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm077_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02 directory --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrr070"
