#!/bin/bash
#
# NAS QUOTAS - clnvrm080
#
# Generated by generate_nas_scripts.py
#
set -e

# This script is idempotent.
# Existing directories are preserved.
# Ownership/mode are corrected only when required.

# --------------------------------------------------------
# QUOTA: clnvrm081
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm081

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm082
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm082

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm083
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm083

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm084
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm084

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm085
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm085

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm086
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm086

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm087
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm080/clnvrm087

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrm080"
