#!/bin/bash
#
# NAS QUOTAS - clnvrm070
#
# Generated by generate_nas_scripts.py
#
set -e

# This script is idempotent.
# Existing directories are preserved.
# Ownership/mode are corrected only when required.

# --------------------------------------------------------
# QUOTA: clnvrm071
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm071

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm072
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm072

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm073
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm073

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm074
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm074

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm075
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm075

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm076
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm076

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm077
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm070/clnvrm077

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrm070"
