#!/bin/bash
#
# NAS FOLDERS / PERMISSIONS / EXPORT - clnvrr070
#
# Generated by generate_nas_scripts.py
#
set -e


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic071rp
# RESOURCE GROUP: clnvrm071
# SERVICE: clnvrm071_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm071/clnvrm071_p02/etc/picata


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic072rp
# RESOURCE GROUP: clnvrm072
# SERVICE: clnvrm072_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm072/clnvrm072_p02/etc/picata


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic073rp
# RESOURCE GROUP: clnvrm073
# SERVICE: clnvrm073_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm073/clnvrm073_p02/etc/picata


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic074rp
# RESOURCE GROUP: clnvrm074
# SERVICE: clnvrm074_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm074/clnvrm074_p02/etc/picata


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic075rp
# RESOURCE GROUP: clnvrm075
# SERVICE: clnvrm075_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm075/clnvrm075_p02/etc/picata


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic076rp
# RESOURCE GROUP: clnvrm076
# SERVICE: clnvrm076_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm076/clnvrm076_p02/etc/picata


################################################
# CLUSTER: clnvrr070
# CLUSTER NAME: TVSNVRCLU070RP
# PICATA RG: tvsnvrpic077rp
# RESOURCE GROUP: clnvrm077
# SERVICE: clnvrm077_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr070/clnvrm077/clnvrm077_p02/etc/picata


################################################
# CLUSTER ROOT NFS EXPORT
################################################

# --------------------------------------------------------
# NFS EXPORT - CLUSTER ROOT ONLY
# --------------------------------------------------------

EXPORT_PATH=/ifs/infstonas001rp/mtr-rec/clnvrr070

# Check whether the cluster-root export already exists.
EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

if [[ -z "$EXPORT_ID" ]]; then
    echo "NFS export does not exist. Creating: $EXPORT_PATH"
    isi nfs exports create "$EXPORT_PATH" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    # Get the newly created export ID.
    EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

    if [[ -z "$EXPORT_ID" ]]; then
        echo "ERROR: NFS export was created but its ID could not be found."
        exit 1
    fi

    echo "NFS export created: $EXPORT_PATH (ID $EXPORT_ID)"
else
    echo "NFS export already exists: $EXPORT_PATH (ID $EXPORT_ID)"
    echo "Updating NFS export parameters..."

    isi nfs exports modify "$EXPORT_ID" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export updated: $EXPORT_PATH (ID $EXPORT_ID)"
fi


echo ""
echo "Completed NAS folders, permissions and NFS export for clnvrr070"
