#!/bin/bash
#
# NAS QUOTAS - clnvrm060
#
# Generated by generate_nas_scripts.py
#
set -e

# This script is idempotent.
# Existing directories are preserved.
# Ownership/mode are corrected only when required.

# --------------------------------------------------------
# QUOTA: clnvrm061
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm061

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm062
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm062

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm063
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm063

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm064
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm064

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm065
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm065

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm066
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm066

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm067
# --------------------------------------------------------

QUOTA_PATH=/ifs/infstonas001mp/mtr-rec/clnvrm060/clnvrm067

echo "Checking quota for $QUOTA_PATH"

if isi quota quotas list --path "$QUOTA_PATH" >/dev/null 2>&1; then
    echo "Quota already exists: $QUOTA_PATH"
else
    echo "Creating quota: $QUOTA_PATH"
    isi quota quotas create "$QUOTA_PATH" --type=directory
fi

isi quota quotas modify "$QUOTA_PATH" --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrm060"
