#!/bin/bash
#
# NAS FOLDERS / PERMISSIONS / EXPORT - clnvrr060
#
# Generated by generate_nas_scripts.py
#
set -e


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic061rp
# RESOURCE GROUP: clnvrm061
# SERVICE: clnvrm061_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm061/clnvrm061_p02/etc/picata


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic062rp
# RESOURCE GROUP: clnvrm062
# SERVICE: clnvrm062_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm062/clnvrm062_p02/etc/picata


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic063rp
# RESOURCE GROUP: clnvrm063
# SERVICE: clnvrm063_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm063/clnvrm063_p02/etc/picata


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic064rp
# RESOURCE GROUP: clnvrm064
# SERVICE: clnvrm064_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm064/clnvrm064_p02/etc/picata


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic065rp
# RESOURCE GROUP: clnvrm065
# SERVICE: clnvrm065_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm065/clnvrm065_p02/etc/picata


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic066rp
# RESOURCE GROUP: clnvrm066
# SERVICE: clnvrm066_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm066/clnvrm066_p02/etc/picata


################################################
# CLUSTER: clnvrr060
# CLUSTER NAME: TVSNVRCLU060RP
# PICATA RG: tvsnvrpic067rp
# RESOURCE GROUP: clnvrm067
# SERVICE: clnvrm067_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr060/clnvrm067/clnvrm067_p02/etc/picata


################################################
# CLUSTER ROOT NFS EXPORT
################################################

# --------------------------------------------------------
# NFS EXPORT - CLUSTER ROOT ONLY
# --------------------------------------------------------

EXPORT_PATH=/ifs/infstonas001rp/mtr-rec/clnvrr060

# Check whether the cluster-root export already exists.
EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

if [[ -z "$EXPORT_ID" ]]; then
    echo "NFS export does not exist. Creating: $EXPORT_PATH"
    isi nfs exports create "$EXPORT_PATH" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    # Get the newly created export ID.
    EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

    if [[ -z "$EXPORT_ID" ]]; then
        echo "ERROR: NFS export was created but its ID could not be found."
        exit 1
    fi

    echo "NFS export created: $EXPORT_PATH (ID $EXPORT_ID)"
else
    echo "NFS export already exists: $EXPORT_PATH (ID $EXPORT_ID)"
    echo "Updating NFS export parameters..."

    isi nfs exports modify "$EXPORT_ID" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export updated: $EXPORT_PATH (ID $EXPORT_ID)"
fi


echo ""
echo "Completed NAS folders, permissions and NFS export for clnvrr060"
