#!/bin/bash
#
# NAS FOLDERS / PERMISSIONS / EXPORT - clnvrr080
#
# Generated by generate_nas_scripts.py
#
set -e


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic081rp
# RESOURCE GROUP: clnvrm081
# SERVICE: clnvrm081_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02/etc/picata


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic082rp
# RESOURCE GROUP: clnvrm082
# SERVICE: clnvrm082_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02/etc/picata


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic083rp
# RESOURCE GROUP: clnvrm083
# SERVICE: clnvrm083_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02/etc/picata


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic084rp
# RESOURCE GROUP: clnvrm084
# SERVICE: clnvrm084_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02/etc/picata


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic085rp
# RESOURCE GROUP: clnvrm085
# SERVICE: clnvrm085_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02/etc/picata


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic086rp
# RESOURCE GROUP: clnvrm086
# SERVICE: clnvrm086_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02/etc/picata


################################################
# CLUSTER: clnvrr080
# CLUSTER NAME: TVSNVRCLU080RP
# PICATA RG: tvsnvrpic087rp
# RESOURCE GROUP: clnvrm087
# SERVICE: clnvrm087_p02
################################################

# Create resource group directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087

# Create service directory
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02

# --------------------------------------------------------
# STANDARD SERVICE DIRECTORIES
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/app
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/data
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/log

# Ownership
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/app
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/data
chown recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc
chown root:wheel /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/log

# Permissions
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/app
chmod 700 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/data
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc
chmod 755 /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/log

# --------------------------------------------------------
# PICATA DIRECTORY STRUCTURE
# --------------------------------------------------------

mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc/picata
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc/picata/area-LQ/alarms
mkdir -p /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc/picata/area-LQ/records

chown -R recorder:recorder /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02/etc/picata


################################################
# CLUSTER ROOT NFS EXPORT
################################################

# --------------------------------------------------------
# NFS EXPORT - CLUSTER ROOT ONLY
# --------------------------------------------------------

EXPORT_PATH=/ifs/infstonas001rp/mtr-rec/clnvrr080

# Check whether the cluster-root export already exists.
EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

if [[ -z "$EXPORT_ID" ]]; then
    echo "NFS export does not exist. Creating: $EXPORT_PATH"
    isi nfs exports create "$EXPORT_PATH" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    # Get the newly created export ID.
    EXPORT_ID="$(isi nfs exports list --zone=mtr-rec --format=csv | awk -F, -v p="$EXPORT_PATH" '$2 == p {print $1; exit}')"

    if [[ -z "$EXPORT_ID" ]]; then
        echo "ERROR: NFS export was created but its ID could not be found."
        exit 1
    fi

    echo "NFS export created: $EXPORT_PATH (ID $EXPORT_ID)"
else
    echo "NFS export already exists: $EXPORT_PATH (ID $EXPORT_ID)"
    echo "Updating NFS export parameters..."

    isi nfs exports modify "$EXPORT_ID" \
        --zone=mtr-rec \
        --read-write-clients=10.101.30.0/23 \
        --root-clients=10.101.30.0/23 \
        --all-dirs=yes

    echo "NFS export updated: $EXPORT_PATH (ID $EXPORT_ID)"
fi


echo ""
echo "Completed NAS folders, permissions and NFS export for clnvrr080"
