#!/bin/bash
#
# NAS QUOTAS - clnvrr080
#
# Generated by generate_nas_scripts.py
#
set -e

# --------------------------------------------------------
# QUOTA: clnvrm081_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm081/clnvrm081_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm082_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm082/clnvrm082_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm083_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm083/clnvrm083_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm084_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm084/clnvrm084_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm085_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm085/clnvrm085_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm086_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm086/clnvrm086_p02 directory --hard-threshold 16TB

# --------------------------------------------------------
# QUOTA: clnvrm087_p02
# --------------------------------------------------------

isi quota quotas create /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02 --type=directory
isi quota quotas modify /ifs/infstonas001rp/mtr-rec/clnvrr080/clnvrm087/clnvrm087_p02 directory --hard-threshold 16TB


echo ""
echo "Completed quotas for clnvrr080"
